### ISSUE TITLE
SV integration test failing

### ISSUE THREAD

**Issue by glebkuznetsov** [churchlab/millstone#337]
======================================================================
FAIL: test_pipeline_and_svs (genome_designer.tests.integration.test_sv_pipeline.TestSVPipeline)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/glebk/Projects/churchlab/genome-designer-v2/genome_designer/../genome_designer/tests/integration/test_sv_pipeline.py", line 118, in test_pipeline_and_svs
    lumpy_variants = get_variants(Dataset.TYPE.VCF_LUMPY)
  File "/home/glebk/Projects/churchlab/genome-designer-v2/genome_designer/../genome_designer/tests/integration/test_sv_pipeline.py", line 103, in get_variants
    svtype=raw_data_dict['INFO_SVTYPE']))
AssertionError: length of INFO_SVLEN > 1: DEL

**Comment by glebkuznetsov** [comment]
Won't fix.
