### ISSUE TITLE
uncaught StopIteration exception in variant_effects.py when no variants called

### ISSUE THREAD

**Issue by glebkuznetsov** [churchlab/millstone#430]

**Comment by woodymit** [comment]
Here's the error traceback in the vcf directory:

Traceback (most recent call last):
  File "/home/wahern/projects/millstone/genome_designer/pipeline/pipeline_runner.py", line 347, in merge_variant_data
    merge_freebayes_parallel(alignment_group)
  File "/home/wahern/projects/millstone/genome_designer/pipeline/variant_calling/freebayes.py", line 206, in merge_freebayes_parallel
    alignment_group, Dataset.TYPE.BWA_ALIGN)
  File "/home/wahern/projects/millstone/genome_designer/pipeline/variant_effects.py", line 333, in run_snpeff
    convert_snpeff_info_fields(snpeff_proc.stdout, fh_out)
  File "/home/wahern/projects/millstone/genome_designer/pipeline/variant_effects.py", line 364, in convert_snpeff_info_fields
    vcf_reader = vcf.Reader(vcf_input_fh)
  File "/home/wahern/projects/millstone/venv/local/lib/python2.7/site-packages/vcf/parser.py", line 282, in __init__
    self._parse_metainfo()
  File "/home/wahern/projects/millstone/venv/local/lib/python2.7/site-packages/vcf/parser.py", line 298, in _parse_metainfo
    line = self.reader.next()
StopIteration
