### ISSUE TITLE
VariantToVariantSet Database Duplicate Key Issue

### ISSUE THREAD

**Issue by glebkuznetsov** [churchlab/millstone#473]
This happens when you re-run an alignment with similar settings.  Something about the same VariantToVariantSet being assigned to the same ExperimentSample or something.  I don't think this actually causes issues since the entry that should be in the db is already there, but there might be a bigger issue around here somewhere.

[2015-02-08 00:51:11,232: ERROR/MainProcess] Task pipeline.variant_calling.find_variants_with_tool[351623db-7f75-4a5b-a4de-6f79ccce023e] raised exception: IntegrityError('duplicate key value violates unique constraint "main_varianttovariantset_samp_varianttovariantset_id_experi_key"\nDETAIL:  Key (varianttovariantset_id, experimentsample_id)=(34, 11) already exists.\n',)
Traceback (most recent call last):
  File "/Users/gleb/Dropbox/Backup/Projects/churchlab/millstone/venv/lib/python2.7/site-packages/celery/task/trace.py", line 233, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/gleb/Dropbox/Backup/Projects/churchlab/millstone/venv/lib/python2.7/site-packages/celery/task/trace.py", line 420, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/gleb/Dropbox/Backup/Projects/churchlab/millstone/genome_designer/main/s3.py", line 43, in wrapper
    return func(*args, **kwargs)
  File "/Users/gleb/Dropbox/Backup/Projects/churchlab/millstone/genome_designer/pipeline/variant_calling/__init__.py", line 146, in find_variants_with_tool
    process_vcf_dataset(alignment_group, vcf_dataset_type)
  File "/Users/gleb/Dropbox/Backup/Projects/churchlab/millstone/genome_designer/pipeline/variant_calling/common.py", line 89, in process_vcf_dataset
    flag_variants_from_bed(alignment_group, Dataset.TYPE.BED_CALLABLE_LOCI)
  File "/Users/gleb/Dropbox/Backup/Projects/churchlab/millstone/genome_designer/pipeline/variant_calling/common.py", line 128, in flag_variants_from_bed
    bed_dataset=callable_loci_bed)
  File "/Users/gleb/Dropbox/Backup/Projects/churchlab/millstone/genome_designer/variants/variant_sets.py", line 200, in add_variants_to_set_from_bed
    variant_uid_to_obj_map, sample_uid_to_obj_map)
  File "/Users/gleb/Dropbox/Backup/Projects/churchlab/millstone/genome_designer/variants/variant_sets.py", line 323, in _perform_add
    sample_uid_to_obj_map[sample_uid])
  File "/Users/gleb/Dropbox/Backup/Projects/churchlab/millstone/venv/lib/python2.7/site-packages/django/db/models/fields/related.py", line 650, in add
    self._add_items(self.source_field_name, self.target_field_name, *objs)
  File "/Users/gleb/Dropbox/Backup/Projects/churchlab/millstone/venv/lib/python2.7/site-packages/django/db/models/fields/related.py", line 739, in _add_items
    for obj_id in new_ids
  File "/Users/gleb/Dropbox/Backup/Projects/churchlab/millstone/venv/lib/python2.7/site-packages/django/db/models/query.py", line 444, in bulk_create
    self._batched_insert(objs_without_pk, fields, batch_size)
  File "/Users/gleb/Dropbox/Backup/Projects/churchlab/millstone/venv/lib/python2.7/site-packages/django/db/models/query.py", line 902, in _batched_insert
    using=self.db)
  File "/Users/gleb/Dropbox/Backup/Projects/churchlab/millstone/venv/lib/python2.7/site-packages/django/db/models/manager.py", line 215, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/Users/gleb/Dropbox/Backup/Projects/churchlab/millstone/venv/lib/python2.7/site-packages/django/db/models/query.py", line 1661, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/gleb/Dropbox/Backup/Projects/churchlab/millstone/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 937, in execute_sql
    cursor.execute(sql, params)
  File "/Users/gleb/Dropbox/Backup/Projects/churchlab/millstone/venv/lib/python2.7/site-packages/django/db/backends/util.py", line 41, in execute
    return self.cursor.execute(sql, params)
  File "/Users/gleb/Dropbox/Backup/Projects/churchlab/millstone/venv/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 56, in execute
    six.reraise(utils.IntegrityError, utils.IntegrityError(*tuple(e.args)), sys.exc_info()[2])
  File "/Users/gleb/Dropbox/Backup/Projects/churchlab/millstone/venv/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 54, in execute
    return self.cursor.execute(query, args)
None: duplicate key value violates unique constraint "main_varianttovariantset_samp_varianttovariantset_id_experi_key"
DETAIL:  Key (varianttovariantset_id, experimentsample_id)=(34, 11) already exists.

**Comment by glebkuznetsov** [comment]
Haven't seen this for a while. Closing.
