### ISSUE TITLE
Error after creating new project

### ISSUE THREAD

**Issue by glebkuznetsov** [churchlab/millstone#512]
I see the fix:

ERROR Internal Server Error: /_/templates/reference_genome_list_controls
Traceback (most recent call last):
  File "/Users/gleb/Dropbox/Backup/Projects/churchlab/millstone/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/gleb/Dropbox/Backup/Projects/churchlab/millstone/genome_designer/main/template_xhrs.py", line 78, in reference_genome_list_controls
    context['show_de_novo'] = int(request.GET.get('showDeNovo'))
TypeError: int() argument must be a string or a number, not 'NoneType'

**Comment by glebkuznetsov** [comment]
Actually Brian's fix of getting rid of showing de novo assemblies in ReferenceGenome list view is more correct and matches overall development.

Fixed in 39e0564919c5bb56cbfc070cae7bca250a4f1a1d.
