### ISSUE TITLE
bootstrap_data.py is broken

### ISSUE THREAD

**Issue by glebkuznetsov** [churchlab/millstone#515]
Alignment fails. Probably because we updated the alignment pipeline a bit.

**Comment by glebkuznetsov** [comment]
This is caused by using the latest version of lumpy scripts (pairend_distro.py). Looks like they changed the interface to one of their functions. I'll probably update our code to match this latest interface and ask everyone to update their local lumpy.

Full error:

    /Users/gleb/Dropbox/Backup/Projects/churchlab/millstone/venv/lib/python2.7/site-packages/numpy/core/_methods.py:55: RuntimeWarning: Mean of empty slice.
      warnings.warn("Mean of empty slice.", RuntimeWarning)
    /Users/gleb/Dropbox/Backup/Projects/churchlab/millstone/venv/lib/python2.7/site-packages/numpy/core/_methods.py:67: RuntimeWarning: invalid value encountered in double_scalars
      ret = ret.dtype.type(ret / rcount)
    /Users/gleb/Dropbox/Backup/Projects/churchlab/millstone/genome_designer/conf/../tools/lumpy/pairend_distro.py:102: RuntimeWarning: invalid value encountered in less
      L = L[L < upper_cutoff]
    Traceback (most recent call last):
      File "/Users/gleb/Dropbox/Backup/Projects/churchlab/millstone/genome_designer/conf/../tools/lumpy/pairend_distro.py", line 106, in <module>
        (removed, upper_cutoff))
    TypeError: %d format: a number is required, not numpy.float64
    Traceback (most recent call last):
      File "/Users/gleb/Dropbox/Backup/Projects/churchlab/millstone/genome_designer/scripts/../pipeline/read_alignment.py", line 161, in align_with_bwa_mem
        opt_processing_mask=opt_processing_mask)
      File "/Users/gleb/Dropbox/Backup/Projects/churchlab/millstone/genome_designer/scripts/../pipeline/read_alignment.py", line 314, in process_sam_bam_file
        sample_alignment, error_output)
      File "/Users/gleb/Dropbox/Backup/Projects/churchlab/millstone/genome_designer/scripts/../pipeline/read_alignment.py", line 485, in compute_insert_metrics
        raw_mean, raw_stdev = mean_and_stdev_str.split('\t')
    ValueError: need more than 1 value to unpack
