### ISSUE TITLE
Divide by zero error during 'Find Insertion Location'

### ISSUE THREAD

**Issue by dbgoodman** [churchlab/millstone#617]
When finding insertion locations for all contigs in the Tenaillon dataset. 
@woodymit 
```
ERROR Internal Server Error: /_/contigs/find_insertion_location
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 25, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "/home/ubuntu/millstone/genome_designer/main/xhr_handlers.py", line 1213, in contigs_find_insertion_location
    contig)
  File "/home/ubuntu/millstone/genome_designer/genome_finish/insertion_placement_read_trkg.py", line 61, in get_insertion_placement_positions
    reads_to_contig_dict)
  File "/home/ubuntu/millstone/genome_designer/genome_finish/insertion_placement_read_trkg.py", line 231, in is_contig_reverse_complement
    direction_agreement) > REVERSED_COMPLEMENTARITY_FRACTION_CUTOFF)
ZeroDivisionError: integer division or modulo by zero
```

**Comment by woodymit** [comment]
Whoops I'm on it

**Comment by woodymit** [comment]
Sent pull request to fix

**Comment by dbgoodman** [comment]
Got farther, but still fails sometimes. New error:

```
ERROR Internal Server Error: /_/contigs/find_insertion_location
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 25, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "/home/ubuntu/millstone/genome_designer/main/xhr_handlers.py", line 1213, in contigs_find_insertion_location
    contig)
  File "/home/ubuntu/millstone/genome_designer/genome_finish/insertion_placement_read_trkg.py", line 75, in get_insertion_placement_positions
    right_ref_endpoints = get_top_clipped_locs(left_clipped)
  File "/home/ubuntu/millstone/genome_designer/genome_finish/insertion_placement_read_trkg.py", line 435, in get_top_clipped_locs
    while included / float(total) < ENDPOINT_FRACTION:
ZeroDivisionError: float division by zero
```

**Comment by dbgoodman** [comment]
@woodymit: Some things are being found though. Will be nice to go through some results with you to see how we can clean it up.
