### ISSUE TITLE
Custom reference genome exported from Geneious causes SnpEff error

### ISSUE THREAD

**Issue by glebkuznetsov** [churchlab/millstone#640]
I'm working with Marc G. to analyze the RC3 sequencing data. He created this Genbank which has 2 chromosomes:

1. Genome with seg19 deleted.
2. Plasmid containing recoded seg19.

https://www.dropbox.com/s/p7w4w4aeksq2ilg/seg19_DEL.gb?dl=0

SnpEff throws an error on upload (although this is not visible to the user, only in millstone-stdout.log). Subsequently, the alignment / variatn calling pipeline fails at the SnpEff step.

You can reproduce the initial upload error on the server with:
    java -jar /home/ubuntu/millstone/genome_designer/tools/snpEff/snpEff.jar build -v -genbank -v a4328420 -c /home/ubuntu/millstone/genome_designer/temp_data/projects/d9521526/ref_genomes/a4328420/snpeff/snpeff.config

        00:00:02.241    Saving database
        java.lang.NullPointerException
                at ca.mcgill.mcb.pcingola.interval.Marker.hashCode(Marker.java:345)
                at java.util.HashMap.hash(HashMap.java:362)
                at java.util.HashMap.getEntry(HashMap.java:462)
                at java.util.HashMap.containsKey(HashMap.java:449)
                at ca.mcgill.mcb.pcingola.serializer.MarkerSerializer.save(MarkerSerializer.java:263)
                at ca.mcgill.mcb.pcingola.serializer.MarkerSerializer.save(MarkerSerializer.java:250)
                at ca.mcgill.mcb.pcingola.interval.IntervalAndSubIntervals.serializeSave(IntervalAndSubIntervals.java:167)
                at ca.mcgill.mcb.pcingola.interval.Gene.serializeSave(Gene.java:271)
                at ca.mcgill.mcb.pcingola.serializer.MarkerSerializer.save(MarkerSerializer.java:270)
                at ca.mcgill.mcb.pcingola.serializer.MarkerSerializer.save(MarkerSerializer.java:298)
                at ca.mcgill.mcb.pcingola.serializer.MarkerSerializer.save(MarkerSerializer.java:314)
                at ca.mcgill.mcb.pcingola.snpEffect.SnpEffectPredictor.save(SnpEffectPredictor.java:476)
                at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdBuild.run(SnpEffCmdBuild.java:296)
                at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEff.run(SnpEff.java:306)
                at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEff.main(SnpEff.java:86)

I tried splitting the Genbank into its 2 constituent "chromosomes".

Upload of the genome-minus-seg19 works, as does alignment. Although alignment to that genome reveals strange issues with SnpEff. See gene annotations here:
<http://ec2-54-84-165-141.compute-1.amazonaws.com/projects/d9521526/analyze/b121f83a/variants?filter=&melt=0>

Alignment against the seg19 plasmid fails.

Can you tell what is wrong with this Genbank @dbgoodman or @woodymit?

**Comment by wannier** [comment]
Very interested in how this plays out.  I’m trying to essentially do this exact thing with our sequencing data for sets 3/19/22/23/43/47.  That’s why I was hunting down a BW380 reference genome.  Gleb or Marc, do you know if this exists or who would know the most about BW380’s sequence?

Thanks,
Tim

**Comment by dbgoodman** [comment]
There is a geneious export option for 'vanilla' gbk features..have you
tried that?

**Comment by glebkuznetsov** [comment]
The error occurs while building the SnpEff db:

    java -jar /home/ubuntu/millstone/genome_designer/tools/snpEff/snpEff.jar build -v -genbank -v a4328420 -c /home/ubuntu/millstone/genome_designer/temp_data/projects/d9521526/ref_genomes/a4328420/snpeff/snpeff.config >> snpeff-test-output.txt 2>&1

[snpeff-test-output.txt](https://github.com/churchlab/millstone/files/145232/snpeff-test-output.txt)

Line numers in the error appear to line up to the old version of the SnpEff code on Github: https://github.com/pcingola/SnpEff/tree/029f8bec685073b85c106ac42a77d5e489f836ad

So there is a NullPointerException occuring at https://github.com/pcingola/SnpEff/blob/029f8bec685073b85c106ac42a77d5e489f836ad/src/main/java/ca/mcgill/mcb/pcingola/serializer/MarkerSerializer.java#L263

Not sure if that helps but putting that there anyway.

**Comment by glebkuznetsov** [comment]
Appears to be fixed with upgrade of SnpEff in 303e4320411de94707d29bdc2e21e447a32dd21f.
