### ISSUE TITLE
Can't support ReferenceGenome with non-ascii character in the name

### ISSUE THREAD

**Issue by glebkuznetsov** [churchlab/millstone#643]
e.g.  C321.∆A (u'C321.\u2206A')

Upload might work, but then any place we need to render fails in adapters.py

```
ERROR Internal Server Error: /_/ref_genomes
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 25, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "/home/ubuntu/millstone/genome_designer/main/xhr_handlers.py", line 1121, in get_ref_genomes
    response_data = adapt_model_to_frontend(ReferenceGenome, filters)
  File "/home/ubuntu/millstone/genome_designer/main/adapters.py", line 61, in adapt_model_to_frontend
    for obj in obj_list]
  File "/home/ubuntu/millstone/genome_designer/main/adapters.py", line 243, in adapt_model_instance_to_frontend
    for field in visible_field_names]
  File "/home/ubuntu/millstone/genome_designer/main/adapters.py", line 291, in get_model_field_fe_representation
    return str(model_field)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2206' in position 5: ordinal not in range(128)
```

**Comment by dbgoodman** [comment]
I think we just give the user an error on upload?
