### ISSUE TITLE
Millstone not collecting unused reads for contig assembly use

### ISSUE THREAD

**Issue by mnapolitano89** [churchlab/millstone#668]

**Comment by glebkuznetsov** [comment]
Can you describe how you figured this out?

**Comment by mnapolitano89** [comment]
The error in the celery logs indicated that it was trying to assemble 0 reads :(

**Comment by glebkuznetsov** [comment]
Cool, wouldn't hurt if you could paste that error and anything relevant
looking above or below.

**Comment by mnapolitano89** [comment]
my inability to know how to use vim makes me do this:
[0.000042] Reading read set file /home/ubuntu/millstone/genome_designer/conf/../temp_data/projects/6690444a/alignment_groups/1f263265/sample_alignments/212c2eef/assembly/1/Sequences;
[0.000049] 0 sequences found
[0.000050] 0 sequences in total.
[0.000061] Writing into roadmap file /home/ubuntu/millstone/genome_designer/conf/../temp_data/projects/6690444a/alignment_groups/1f263265/sample_alignments/212c2eef/assembly/1/Roadmaps...


[2016-05-26 16:32:50,647: WARNING/Worker-4] velvetg cmd:
[2016-05-26 16:32:50,647: WARNING/Worker-4] /home/ubuntu/millstone/genome_designer/conf/../tools/velvet/velvetg /home/ubuntu/millstone/genome_designer/conf/../temp_data/projects/6690444a/alignment_groups/1f263265/sample_alignments/212c2eef/assembly/1 -ins_length 284 -exp_cov 22.7934022229 -ins_length_sd 233 -cov_cutoff 5.69835055573 -min_contig_lgth 200 -read_trkg yes
[0.000000] Reading roadmap file /home/ubuntu/millstone/genome_designer/conf/../temp_data/projects/6690444a/alignment_groups/1f263265/sample_alignments/212c2eef/assembly/1/Roadmaps

[0.000171] Initial node count 0
[0.000171] Removed 0 null nodes
[0.000171] Concatenation over!
[0.000172] Removing reference contigs with coverage < 5.698351...
[0.000172] Concatenation...
[0.000173] Renumbering nodes
[0.000173] Initial node count 0
[0.000173] Removed 0 null nodes
[0.000174] Concatenation over!
[0.000184] Writing contigs into /home/ubuntu/millstone/genome_designer/conf/../temp_data/projects/6690444a/alignment_groups/1f263265/sample_alignments/212c2eef/assembly/1/contigs.fa...
[0.000194] Writing into stats file /home/ubuntu/millstone/genome_designer/conf/../temp_data/projects/6690444a/alignment_groups/1f263265/sample_alignments/212c2eef/assembly/1/stats.txt...
[0.000212] Writing into graph file /home/ubuntu/millstone/genome_designer/conf/../temp_data/projects/6690444a/alignment_groups/1f263265/sample_alignments/212c2eef/assembly/1/LastGraph...
[0.000237] EMPTY GRAPH

Final graph has 0 nodes and n50 of 0, max 0, total 0, using 0/0 reads
[2016-05-26 16:32:50,668: ERROR/MainProcess] Task genome_finish.assembly.generate_contigs[dc5d7eb8-d7e4-431b-b817-f75c6029548b] raised unexpected: IndexError('list index out of range',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/ubuntu/millstone/genome_designer/genome_finish/celery_task_decorator.py", line 57, in wrapper
    raise exc
IndexError: list index out of range
[2016-05-26 16:32:52,890: INFO/MainProc
