### ISSUE TITLE
Contig assembly on bootstrap data fails

### ISSUE THREAD

**Issue by glebkuznetsov** [churchlab/millstone#682]
1. With celery running:

        ./scripts/bootstrap_data.py full

2. Start server and navigate to Project:recoli, Alignment: test_align, and start contig assembly for some smaple (e.g. Sample 0).

3. Fails. Error from celery log:

Final graph has 0 nodes and n50 of 0, max 0, total 0, using 0/0 reads
[2016-06-20 13:17:45,106: ERROR/MainProcess] Task genome_finish.assembly.generate_contigs[85a7ea31-fc6b-4313-b5d9-e2d00ce9210f] raised unexpected: IndexError('list index out of range',)
Traceback (most recent call last):
  File "/Users/gleb/Dropbox/Backup/Projects/churchlab/millstone/venv/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/gleb/Dropbox/Backup/Projects/churchlab/millstone/venv/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/gleb/Dropbox/Backup/Projects/churchlab/millstone/genome_designer/genome_finish/celery_task_decorator.py", line 56, in wrapper
    raise exc
IndexError: list index out of range
[2016-06-20 13:17:46,955: ERROR/Worker-4] Chord '570fc618-bc15-4b7e-bf33-3d251643f60e' raised: IndexError('list index out of range',)
Traceback (most recent call last):
  File "/Users/gleb/Dropbox/Backup/Projects/churchlab/millstone/venv/lib/python2.7/site-packages/celery/app/builtins.py", line 82, in unlock_chord
    culprit = next(deps._failed_join_report())
StopIteration

**Comment by dbgoodman** [comment]
Fixed by ff8aa3d.
