### ISSUE TITLE
ALIGNMENT PIPELINE ERROR

### ISSUE THREAD

**Issue by seamyname** [churchlab/millstone#711]
After uploading the Fastq file and ref genome (.gnk), submit the Alignments mission. Then it shows ERROR, and I open the 'bwa_align.error' file and see the following error. I'm not sure what's going on and hope to get your answer.

##############################################
The input is probably truncated.
Killed
Segmentation fault (core dumped)
Traceback (most recent call last):
  File "/home/ubuntu/millstone/genome_designer/pipeline/read_alignment.py", line 156, in align_with_bwa_mem
    opt_processing_mask=opt_processing_mask)
  File "/home/ubuntu/millstone/genome_designer/pipeline/read_alignment.py", line 278, in process_sam_bam_file
    subprocess.check_call(sort_rmdup_cmd, shell=True, stderr=error_output)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '/home/ubuntu/millstone/genome_designer/conf/../tools/samtools/samtools sort -o /home/ubuntu/millstone/genome_designer/conf/../temp_data/projects/197f3ad5/alignment_groups/a706a96f/sample_alignments/72eb1c40/bwa_align.bam /home/ubuntu/millstone/genome_designer/conf/../temp_data/projects/197f3ad5/alignment_groups/a706a96f/sample_alignments/72eb1c40/bwa_align.sorted.tmp.bam|/home/ubuntu/millstone/genome_designer/conf/../tools/samtools/samtools rmdup - /home/ubuntu/millstone/genome_designer/conf/../temp_data/projects/197f3ad5/alignment_groups/a706a96f/sample_alignments/72eb1c40/bwa_align.sorted.bam' returned non-zero exit status 139
==END OF ==

**Comment by dbgoodman** [comment]
Hi, 

It looks like samtools seg-faulted during the sorting of the bam alignment. Is it possible that the machine you are running on does not have enough memory or disk space? 

If that is not the issue, and you want to try to debug yourself, you could inspect the bam file at that path (`home/ubuntu/millstone/genome_designer/conf/../temp_data/projects/197f3ad5/alignment_groups/a706a96f/sample_alignments/72eb1c40/bwa_align.bam`) to see if it is truncated/corrupted/aligned as expected, etc. 

Good luck!

**Comment by seamyname** [comment]
Thank you very much for your suggestion.
 After we increased the memory, Millstone ran fine and completed the Job.
